2024-04-18 16:36:10,036 - Log.py[line:36] - ERROR: local variable 'result1' referenced before assignment
