{"name": "连接蓝牙", "status": "failed", "statusDetails": {"message": "AssertionError: assert False == True", "trace": "self = <DB_Autotest.main.TestIVI object at 0x000002BB08620670>\n\n    @allure.id(\"test_10_connect_bluetooth\")\n    @allure.title(\"连接蓝牙\")\n    @allure.description(\"\"\"\n        TestId:\n            test_10_connect_bluetooth\n        TestTitle:\n            连接蓝牙\n        TestDescription:\n            连接蓝牙\n        TestPrecondition:\n            1、周边存在蓝牙名为test,且已经连接过此蓝牙设备\n        TestStep:\n            1、连接test蓝牙设备\n        TestExpectation:\n            1、蓝牙连接成功\n                \"\"\")\n    def test_10_connect_bluetooth(self):\n        result = self.a19.connect_bluetooth()\n>       assert result == True\nE       assert False == True\n\nmain.py:235: AssertionError"}, "description": "\n        TestId:\n            test_10_connect_bluetooth\n        TestTitle:\n            连接蓝牙\n        TestDescription:\n            连接蓝牙\n        TestPrecondition:\n            1、周边存在蓝牙名为test,且已经连接过此蓝牙设备\n        TestStep:\n            1、连接test蓝牙设备\n        TestExpectation:\n            1、蓝牙连接成功\n                ", "attachments": [{"name": "log", "source": "a3a41dee-48ca-4fcc-a2c7-e23e276c3ff4-attachment.txt", "type": "text/plain"}], "start": 1713419389182, "stop": 1713419425555, "uuid": "3804acae-f5d6-46a0-8772-79522cc0fa84", "historyId": "bccde42dd955cc7d5182b815133bbf37", "testCaseId": "bccde42dd955cc7d5182b815133bbf37", "fullName": "main.TestIVI#test_10_connect_bluetooth", "labels": [{"name": "as_id", "value": "test_10_connect_bluetooth"}, {"name": "suite", "value": "main"}, {"name": "subSuite", "value": "TestIVI"}, {"name": "host", "value": "test-1"}, {"name": "thread", "value": "21340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}